// Translation dictionary — ONE place for all UI strings.
//
// Structure: every key maps to { en, ar }. Add a key here, then use it in a
// component via `const { t } = useT(); t("your.key")`. Keys are namespaced by
// area (common.*, nav.*, alerts.*, …) so related strings stay together. Data
// values (driver names, etc.) are NOT translated — only UI chrome.
//
// To add/edit wording: change the en/ar text below. To add a new string: add a
// new key and reference it with t("...").

export type Lang = "en" | "ar";

export const dict: Record<string, { en: string; ar: string }> = {
  // --- common ---------------------------------------------------------------
  "common.save": { en: "Save", ar: "حفظ" },
  "toast.created": { en: "Created successfully", ar: "تم الإنشاء بنجاح" },
  "toast.saved": { en: "Saved successfully", ar: "تم الحفظ بنجاح" },
  "toast.updated": { en: "Updated successfully", ar: "تم التحديث بنجاح" },
  "toast.deleted": { en: "Deleted successfully", ar: "تم الحذف بنجاح" },
  "common.cancel": { en: "Cancel", ar: "إلغاء" },
  "common.create": { en: "Create", ar: "إنشاء" },
  "common.delete": { en: "Delete", ar: "حذف" },
  "common.edit": { en: "Edit", ar: "تعديل" },
  "common.done": { en: "Done", ar: "تم" },
  "common.retry": { en: "Retry", ar: "إعادة المحاولة" },
  "common.loading": { en: "Loading…", ar: "جارٍ التحميل…" },
  "common.active": { en: "active", ar: "نشط" },
  "common.inactive": { en: "inactive", ar: "غير نشط" },
  "common.suspended": { en: "suspended", ar: "موقوف" },
  "common.expired": { en: "expired", ar: "منتهٍ" },
  "common.online": { en: "online", ar: "متصل" },
  "common.offline": { en: "offline", ar: "غير متصل" },
  "common.yes": { en: "yes", ar: "نعم" },
  "common.no": { en: "no", ar: "لا" },
  "common.status": { en: "Status", ar: "الحالة" },
  "common.actions": { en: "Actions", ar: "إجراءات" },
  "common.name": { en: "Name", ar: "الاسم" },
  "common.email": { en: "Email", ar: "البريد الإلكتروني" },
  "common.phone": { en: "Phone", ar: "الهاتف" },
  "common.username": { en: "Username", ar: "اسم المستخدم" },
  "common.password": { en: "Password", ar: "كلمة المرور" },
  "common.date": { en: "Date", ar: "التاريخ" },
  "common.type": { en: "Type", ar: "النوع" },
  "common.detail": { en: "Detail", ar: "التفاصيل" },
  "common.driver": { en: "Driver", ar: "السائق" },
  "common.supervisor": { en: "Supervisor", ar: "المشرف" },
  "common.busDriver": { en: "Bus driver", ar: "سائق الحافلة" },
  "common.vehicle": { en: "Vehicle", ar: "المركبة" },
  "common.route": { en: "Route", ar: "المسار" },
  "common.organization": { en: "Organization", ar: "المؤسسة" },
  "common.required": { en: "required", ar: "مطلوب" },
  "common.role": { en: "Role", ar: "الدور" },
  "common.address": { en: "Address", ar: "العنوان" },
  "common.maxDevices": { en: "Max devices", ar: "أقصى عدد للأجهزة" },
  "common.activeHdr": { en: "Active", ar: "نشط" },
  "common.none": { en: "No records yet.", ar: "لا توجد سجلات بعد." },
  "common.failed": { en: "Action failed.", ar: "فشل الإجراء." },
  "common.loadFailed": { en: "Failed to load.", ar: "تعذّر التحميل." },
  "common.createAnother": { en: "Create another", ar: "إنشاء آخر" },
  "common.from": { en: "From", ar: "من" },
  "common.to": { en: "To", ar: "إلى" },

  // --- org-create / org actions (super-admin) -------------------------------
  "orgs.ownerUsername": { en: "Owner username", ar: "اسم مستخدم المالك" },
  "orgs.ownerPassword": { en: "Owner password", ar: "كلمة مرور المالك" },
  "orgs.subscriptionExpiry": { en: "Subscription expiry", ar: "انتهاء الاشتراك" },
  "orgs.created": { en: "Organization created. Owner login to hand to the client:", ar: "تم إنشاء المؤسسة. بيانات دخول المالك لتسليمها للعميل:" },
  "orgs.viewDrivers": { en: "View drivers", ar: "عرض السائقين" },
  "orgs.viewUsers": { en: "View users", ar: "عرض المستخدمين" },
  "orgs.loginAs": { en: "Log in as this org", ar: "الدخول كهذه المؤسسة" },
  "orgs.deleteOrg": { en: "Delete org", ar: "حذف المؤسسة" },
  "orgs.deleteOrgTitle": { en: "Delete organization", ar: "حذف المؤسسة" },
  "orgs.deleteWarnPre": { en: "This permanently deletes", ar: "سيؤدي هذا إلى حذف نهائي لـ" },
  "orgs.deleteWarnPost": { en: "— all its users (and their logins), vehicles, routes, trips, assignments, alerts, and payments. This cannot be undone.", ar: "— جميع مستخدميها (وبيانات دخولهم) والمركبات والمسارات والرحلات والتكليفات والتنبيهات والمدفوعات. لا يمكن التراجع عن ذلك." },
  "orgs.deleteTypePre": { en: "Type", ar: "اكتب" },
  "orgs.deleteTypePost": { en: "to confirm", ar: "للتأكيد" },
  "orgs.deletePermanently": { en: "Delete permanently", ar: "حذف نهائي" },
  "orgs.deleting": { en: "Deleting…", ar: "جارٍ الحذف…" },
  "orgs.noneInOrg": { en: "None in this organization.", ar: "لا يوجد في هذه المؤسسة." },

  // --- org detail (super-admin) --------------------------------------------
  "orgsd.editSubscription": { en: "Edit subscription", ar: "تعديل الاشتراك" },
  "orgsd.driversVehicles": { en: "Drivers / Vehicles", ar: "السائقون / المركبات" },
  "orgsd.bannerPre": { en: "This organization is", ar: "هذه المؤسسة" },
  "orgsd.bannerPost": { en: "— its users cannot sign in.", ar: "— لا يمكن لمستخدميها تسجيل الدخول." },
  "orgsd.usersFrozen": { en: "Its users will be blocked from signing in.", ar: "سيُمنع مستخدموها من تسجيل الدخول." },

  // --- platform users (super-admin) ----------------------------------------
  "users.newPlatformUser": { en: "New platform user", ar: "مستخدم منصّة جديد" },
  "users.deleteConfirmPre": { en: "Delete platform user", ar: "حذف مستخدم المنصّة" },
  "users.deleteConfirmPost": { en: "? This removes their login.", ar: "؟ سيؤدي هذا إلى إزالة تسجيل دخوله." },

  // --- assignments extras ---------------------------------------------------
  "assign.shiftLabel": { en: "Shift label", ar: "اسم الوردية" },
  "assign.startTime": { en: "Start time", ar: "وقت البدء" },

  // --- vehicles extras ------------------------------------------------------
  "vehicles.plateNumber": { en: "Plate number", ar: "رقم اللوحة" },

  // --- routes extras --------------------------------------------------------
  "routes.lat": { en: "Lat", ar: "خط العرض" },
  "routes.lng": { en: "Lng", ar: "خط الطول" },
  "routes.dwell": { en: "Waiting", ar: "الانتظار" },
  "routes.noStops": { en: "No stops.", ar: "لا توجد محطات." },
  "routes.stop": { en: "Stop", ar: "محطة" },
  "routes.searchPlace": { en: "Search a place…", ar: "ابحث عن مكان…" },
  "routes.search": { en: "Search", ar: "بحث" },
  "routes.clickToDrop": { en: "Search a place or click the map to drop stops.", ar: "ابحث عن مكان أو انقر على الخريطة لإضافة محطات." },
  "routes.noStopsYet": { en: "No stops yet — search or click the map.", ar: "لا توجد محطات بعد — ابحث أو انقر على الخريطة." },
  "routes.needTwoStops": { en: "Add at least 2 stops.", ar: "أضف محطتين على الأقل." },
  "routes.needName": { en: "Enter a route name.", ar: "أدخل اسم المسار." },
  "routes.routing": { en: "routing…", ar: "جارٍ الحساب…" },
  "routes.dwellMin": { en: "Waiting (min)", ar: "الانتظار (دقيقة)" },
  "routes.routeNamePh": { en: "e.g. Downtown Loop", ar: "مثال: حلقة وسط البلد" },
  "routes.stopNamePh": { en: "Stop name", ar: "اسم المحطة" },

  // --- map (shared) ---------------------------------------------------------
  "map.tokenMissing": { en: "Map unavailable — Mapbox token not set in .env.local.", ar: "الخريطة غير متاحة — لم يتم ضبط رمز Mapbox في .env.local." },
  "map.layers": { en: "Map style", ar: "نمط الخريطة" },
  "map.style.auto": { en: "Auto (theme)", ar: "تلقائي (السمة)" },
  "map.style.streets": { en: "Streets", ar: "الشوارع" },
  "map.style.satellite": { en: "Satellite", ar: "قمر صناعي" },
  "map.style.satelliteStreets": { en: "Satellite Streets", ar: "قمر صناعي + شوارع" },
  "map.style.light": { en: "Light", ar: "فاتح" },
  "map.style.dark": { en: "Dark", ar: "داكن" },
  "map.style.outdoors": { en: "Outdoors", ar: "الطبيعة" },

  // --- route editor (reworked) ---------------------------------------------
  "routes.basics": { en: "Route basics", ar: "أساسيات المسار" },
  "routes.totals": { en: "Totals (auto)", ar: "الإجماليات (تلقائي)" },
  "routes.totalTime": { en: "Total time", ar: "إجمالي الوقت" },
  "routes.startTime": { en: "Start time (stop 1)", ar: "وقت الانطلاق (المحطة 1)" },
  "routes.arrival": { en: "Arrival", ar: "الوصول" },
  "routes.searchGoogle": { en: "Search a place (Google)…", ar: "ابحث عن مكان (Google)…" },
  "routes.googleMissing": { en: "Search needs NEXT_PUBLIC_GOOGLE_MAPS_API_KEY in .env.local.", ar: "يتطلب البحث ضبط NEXT_PUBLIC_GOOGLE_MAPS_API_KEY في .env.local." },
  "routes.mapHint": { en: "Click empty map to add a stop · click a marker for actions · click the line to insert · press-drag to pan.", ar: "انقر على الخريطة الفارغة لإضافة محطة · انقر على العلامة للإجراءات · انقر على الخط للإدراج · اضغط واسحب للتحريك." },
  "routes.move": { en: "Move", ar: "تحريك" },
  "routes.duplicate": { en: "Duplicate", ar: "تكرار" },
  "routes.moveHint": { en: "Drag the highlighted stop, then release to drop it.", ar: "اسحب المحطة المميزة ثم أفلتها لتثبيتها." },
  "routes.addHere": { en: "Add a stop here", ar: "أضف محطة هنا" },
  "routes.dragToReorder": { en: "Drag to reorder", ar: "اسحب لإعادة الترتيب" },
  "routes.invalidArrival": { en: "before previous stop", ar: "قبل المحطة السابقة" },
  "routes.min": { en: "min", ar: "دقيقة" },
  "routes.remove": { en: "Remove", ar: "إزالة" },
  "routes.undo": { en: "Undo", ar: "تراجع" },
  "routes.removed": { en: "Stop removed", ar: "تمت إزالة المحطة" },
  "routes.search.noResults": { en: "No matching places.", ar: "لا توجد أماكن مطابقة." },
  "routes.search.errAuth": { en: "Search blocked: the Google key was rejected. Add this site's URL (e.g. http://localhost:3003/*) to the key's website restrictions in Google Cloud.", ar: "تم حظر البحث: تم رفض مفتاح Google. أضف عنوان هذا الموقع (مثل http://localhost:3003/*) إلى قيود المواقع للمفتاح في Google Cloud." },
  "routes.search.errDenied": { en: "Search denied: enable the Places API for this key in Google Cloud (Places API and/or Places API New).", ar: "تم رفض البحث: فعّل Places API لهذا المفتاح في Google Cloud (Places API و/أو Places API New)." },
  "routes.search.errLoad": { en: "Couldn't load Google Maps. Check your network connection and the key.", ar: "تعذّر تحميل خرائط Google. تحقق من اتصال الشبكة والمفتاح." },
  "routes.search.errUnknown": { en: "Search failed — see the browser console for details.", ar: "فشل البحث — راجع وحدة تحكم المتصفح للتفاصيل." },
  "routes.color": { en: "Route color", ar: "لون المسار" },
  "routes.customColor": { en: "Custom", ar: "مخصص" },
  "routes.addStopHere": { en: "Add stop", ar: "أضف محطة" },
  "routes.reshape": { en: "Drag to reroute", ar: "اسحب لتغيير المسار" },
  "routes.reshapeHint": { en: "Drag the handle onto a different street, then release to reroute this segment.", ar: "اسحب المقبض إلى شارع آخر ثم أفلته لإعادة توجيه هذا المقطع." },
  "routes.pendingAddHint": { en: "Click the + to add a stop here, or click elsewhere to cancel.", ar: "انقر على + لإضافة محطة هنا، أو انقر في مكان آخر للإلغاء." },
  "routes.viewAll": { en: "View all routes", ar: "عرض كل المسارات" },
  "routes.allRoutes": { en: "All routes", ar: "كل المسارات" },
  "routes.noGeometry": { en: "No drawn path yet", ar: "لا يوجد مسار مرسوم بعد" },
  "routes.editRoute": { en: "Edit route", ar: "تعديل المسار" },
  "routes.deleteRoute": { en: "Delete route", ar: "حذف المسار" },
  "routes.deleteConfirm": { en: "Delete this route and all its stops? This can't be undone.", ar: "حذف هذا المسار وكل محطاته؟ لا يمكن التراجع عن هذا الإجراء." },

  // --- reports extras -------------------------------------------------------
  "reports.kilometers": { en: "Kilometers — by vehicle / by driver", ar: "الكيلومترات — حسب المركبة / السائق" },
  "reports.speed": { en: "Speed", ar: "السرعة" },
  "reports.kmShort": { en: "Kilometers", ar: "الكيلومترات" },
  "reports.bus": { en: "Bus", ar: "الحافلة" },
  "reports.maxKmh": { en: "Max km/h", ar: "أقصى كم/س" },
  "reports.avgKmh": { en: "Avg km/h", ar: "متوسط كم/س" },
  "reports.speedingAlerts": { en: "Speeding alerts", ar: "تنبيهات السرعة" },
  "reports.pickType": { en: "Pick at least one report type.", ar: "اختر نوع تقرير واحدًا على الأقل." },
  "reports.customNeedsDates": { en: "Custom range needs both dates.", ar: "النطاق المخصص يتطلب التاريخين." },

  // --- full view extras -----------------------------------------------------
  "full.updated": { en: "updated", ar: "محدّث منذ" },
  "full.secShort": { en: "s", ar: "ث" },
  "full.minShort": { en: "m", ar: "د" },
  "full.hrShort": { en: "h", ar: "س" },
  "full.noPings": { en: "no pings yet", ar: "لا توجد إشارات بعد" },

  // --- settings extras ------------------------------------------------------
  "settings.alwaysOnHelp": { en: "The public link shows live position whenever a trip is running.", ar: "يعرض الرابط العام الموقع المباشر عند وجود رحلة جارية." },
  "settings.windowHelp": { en: "Outside this window the public link shows “tracking resumes at <start>” instead of a position.", ar: "خارج هذه الفترة يعرض الرابط العام «يُستأنف التتبّع في <البداية>» بدلًا من الموقع." },

  // --- nav ------------------------------------------------------------------
  "nav.dashboard": { en: "Dashboard", ar: "الرئيسية" },
  "nav.fullView": { en: "Full View", ar: "العرض الكامل" },
  "nav.history": { en: "History", ar: "السجل" },
  "nav.passengers": { en: "Passengers", ar: "الركاب" },
  "nav.grpMonitoring": { en: "Monitoring", ar: "المراقبة" },
  "nav.grpManagement": { en: "Management", ar: "الإدارة" },
  "nav.grpOperations": { en: "Operations", ar: "العمليات" },
  "pax.subtitle": { en: "Students who track their route's buses.", ar: "الطلاب الذين يتتبعون حافلات مسارهم." },
  "pax.newPassenger": { en: "New passenger", ar: "راكب جديد" },
  "pax.editPassenger": { en: "Edit passenger", ar: "تعديل الراكب" },
  "pax.studentName": { en: "Student name", ar: "اسم الطالب" },
  "pax.universityId": { en: "University ID", ar: "الرقم الجامعي" },
  "pax.route": { en: "Route", ar: "المسار" },
  "pax.searchRoute": { en: "Search routes…", ar: "ابحث في المسارات…" },
  "pax.none": { en: "No passengers yet.", ar: "لا يوجد ركاب بعد." },
  "pax.deleteConfirm": { en: "Delete this passenger? Their login is removed too.", ar: "حذف هذا الراكب؟ سيُحذف حسابه أيضًا." },
  "pax.loginTitle": { en: "Passenger login created", ar: "تم إنشاء حساب الراكب" },
  "pax.loginNote": { en: "They log in with this email and the temporary password below, and must change it on first login.", ar: "يسجّل الدخول بهذا البريد وكلمة المرور المؤقتة أدناه، ويجب تغييرها عند أول دخول." },
  "pax.tempPassword": { en: "Temporary password", ar: "كلمة مرور مؤقتة" },
  "pax.mustChange": { en: "Must change on first login", ar: "يجب تغييرها عند أول تسجيل دخول" },
  "pax.bulk": { en: "Bulk upload", ar: "رفع جماعي" },
  "pax.downloadTemplate": { en: "Download template", ar: "تنزيل القالب" },
  "pax.upload": { en: "Upload CSV", ar: "رفع ملف CSV" },
  "pax.bulkResult": { en: "{created} created, {failed} failed.", ar: "تم إنشاء {created}، وفشل {failed}." },
  "pax.rowError": { en: "Row {row} ({email}): {error}", ar: "الصف {row} ({email}): {error}" },
  "hist.subtitle": { en: "Replay past trips — actual path vs planned route.", ar: "أعد تشغيل الرحلات السابقة — المسار الفعلي مقابل المخطط." },
  "hist.drivers": { en: "Drivers", ar: "السائقون" },
  "hist.vehicles": { en: "Vehicles", ar: "المركبات" },
  "hist.all": { en: "All", ar: "الكل" },
  "hist.load": { en: "Load", ar: "تحميل" },
  "hist.noTrips": { en: "No trips in this range.", ar: "لا توجد رحلات في هذه الفترة." },
  "hist.trips": { en: "trips", ar: "رحلة" },
  "hist.actualPath": { en: "Actual path", ar: "المسار الفعلي" },
  "hist.plannedRoute": { en: "Planned route", ar: "المسار المخطط" },
  "hist.noPath": { en: "No recorded path for this trip.", ar: "لا يوجد مسار مُسجّل لهذه الرحلة." },
  "hist.selectTrip": { en: "Select a trip to replay it on the map.", ar: "اختر رحلة لإعادة تشغيلها على الخريطة." },
  "hist.ongoing": { en: "ongoing", ar: "جارية" },
  "hist.scrubHint": { en: "Drag to replay", ar: "اسحب لإعادة التشغيل" },
  "hist.stopsTitle": { en: "Stops & waiting times", ar: "المحطات وأوقات الانتظار" },
  "hist.noStopVisits": { en: "No recorded stop visits for this trip.", ar: "لا توجد زيارات محطات مُسجّلة لهذه الرحلة." },
  "hist.arrived": { en: "Arrived", ar: "الوصول" },
  "hist.waited": { en: "Waited", ar: "الانتظار" },
  "hist.planned": { en: "planned", ar: "مخطط" },
  "hist.stillThere": { en: "still there", ar: "ما زال هناك" },
  "nav.drivers": { en: "Drivers", ar: "السائقون" },
  "nav.supervisors": { en: "Supervisors", ar: "المشرفون" },
  "nav.busDrivers": { en: "Bus Drivers", ar: "سائقو الحافلات" },
  "nav.students": { en: "Students", ar: "الطلاب" },
  "bulk.template": { en: "Download template", ar: "تنزيل القالب" },
  "bulk.import": { en: "Import", ar: "استيراد" },
  "bulk.importing": { en: "Importing…", ar: "جارٍ الاستيراد…" },
  "bulk.created": { en: "created", ar: "أُنشئ" },
  "bulk.failed": { en: "failed", ar: "فشل" },
  "bulk.row": { en: "Row", ar: "الصف" },
  "bulk.empty": { en: "No rows found in the file.", ar: "لا توجد صفوف في الملف." },
  "nav.attendance": { en: "Attendance", ar: "الحضور" },
  "nav.changeRequests": { en: "Change Requests", ar: "طلبات التغيير" },
  "nav.profileRequests": { en: "Profile Requests", ar: "طلبات تعديل البيانات" },
  "nav.parentReports": { en: "Parent Reports", ar: "بلاغات أولياء الأمور" },
  "nav.parents": { en: "Parents", ar: "أولياء الأمور" },
  "nav.logs": { en: "Logs", ar: "السجلات" },
  "logs.title": { en: "Event Logs", ar: "سجل الأحداث" },
  "logs.subtitleToday": { en: "Live feed of today's driver events.", ar: "بث مباشر لأحداث السائقين اليوم." },
  "logs.subtitleAll": { en: "All recorded driver events, newest first.", ar: "كل أحداث السائقين المسجّلة، الأحدث أولاً." },
  "logs.today": { en: "Today (live)", ar: "اليوم (مباشر)" },
  "logs.all": { en: "Full logs", ar: "السجل الكامل" },
  "logs.none": { en: "No events yet.", ar: "لا توجد أحداث بعد." },
  "logs.noneToday": { en: "No events today.", ar: "لا توجد أحداث اليوم." },
  "logs.on": { en: "on bus", ar: "على حافلة" },
  "logs.route": { en: "route", ar: "مسار" },
  "logs.live": { en: "Live · updates every 15s", ar: "مباشر · يُحدَّث كل ١٥ ثانية" },
  "logs.driverEvents": { en: "Recent events", ar: "الأحداث الأخيرة" },
  "logs.viewEvents": { en: "View events", ar: "عرض الأحداث" },
  "logs.hideEvents": { en: "Hide events", ar: "إخفاء الأحداث" },
  "parents.title": { en: "Parents", ar: "أولياء الأمور" },
  "parents.subtitle": { en: "Parents and the children linked to each.", ar: "أولياء الأمور والأبناء المرتبطون بكل منهم." },
  "parents.none": { en: "No parents yet.", ar: "لا يوجد أولياء أمور بعد." },
  "parents.search": { en: "Search by name or email…", ar: "ابحث بالاسم أو البريد…" },
  "parents.noMatch": { en: "No parents match your search.", ar: "لا يوجد أولياء أمور مطابقون." },
  "parents.children": { en: "Children", ar: "الأبناء" },
  "parents.noChildren": { en: "No children linked.", ar: "لا يوجد أبناء مرتبطون." },
  "parents.noRoute": { en: "No route", ar: "بدون مسار" },
  "parents.noDropOff": { en: "No drop-off stop", ar: "بدون محطة نزول" },
  "parents.count": { en: "parents", ar: "ولي أمر" },
  "nav.performance": { en: "Performance", ar: "الأداء" },
  "perf.title": { en: "Performance", ar: "الأداء" },
  "perf.subtitle": { en: "Speeding, route compliance & schedule adherence per supervisor/trip.", ar: "السرعة والالتزام بالمسار والمواعيد لكل مشرف/رحلة." },
  "perf.none": { en: "No performance data yet. It builds as trips are ended.", ar: "لا توجد بيانات بعد. تُبنى عند إنهاء الرحلات." },
  "perf.supervisors": { en: "By supervisor", ar: "حسب المشرف" },
  "perf.trips": { en: "trips", ar: "رحلات" },
  "perf.tripsTitle": { en: "By trip", ar: "حسب الرحلة" },
  "perf.speeding": { en: "Speeding", ar: "تجاوز السرعة" },
  "perf.offRoute": { en: "Off-route", ar: "خارج المسار" },
  "perf.onTimePct": { en: "On-time", ar: "في الوقت" },
  "perf.late": { en: "Late stops", ar: "محطات متأخرة" },
  "perf.avgDelay": { en: "Avg delay", ar: "متوسط التأخير" },
  "perf.date": { en: "Date", ar: "التاريخ" },
  "perf.supervisor": { en: "Supervisor", ar: "المشرف" },
  "perf.route": { en: "Route", ar: "المسار" },
  "perf.min": { en: "min", ar: "دقيقة" },
  "hist.tripLog": { en: "Trip log", ar: "سجل الرحلة" },
  "hist.morning": { en: "Morning", ar: "صباحًا" },
  "hist.afternoon": { en: "Afternoon", ar: "بعد الظهر" },
  "hist.pickup": { en: "First pickup", ar: "أول ركوب" },
  "hist.schoolArrival": { en: "School arrival", ar: "الوصول للمدرسة" },
  "hist.homeArrival": { en: "Home drop-off", ar: "الوصول للمنزل" },
  "nav.studentReports": { en: "Student Reports", ar: "بلاغات الطلاب" },
  "prep.titleStudent": { en: "Student Reports", ar: "بلاغات الطلاب" },
  "prep.title": { en: "Parent Reports", ar: "بلاغات أولياء الأمور" },
  "prep.subtitle": { en: "Issues reported by parents.", ar: "المشكلات التي أبلغ عنها أولياء الأمور." },
  "prep.none": { en: "No reports.", ar: "لا توجد بلاغات." },
  "prep.open": { en: "Open", ar: "مفتوح" },
  "prep.resolved": { en: "Resolved", ar: "تم الحل" },
  "prep.all": { en: "All", ar: "الكل" },
  "prep.resolve": { en: "Mark resolved", ar: "تعليم كمحلول" },
  "prep.resolvedToast": { en: "Report resolved", ar: "تم حل البلاغ" },
  "prep.about": { en: "About", ar: "بخصوص" },
  "prep.route": { en: "Route", ar: "المسار" },
  "prep.noContact": { en: "No contact info", ar: "لا توجد بيانات اتصال" },
  "prep.noPhone": { en: "No phone", ar: "لا يوجد هاتف" },
  "nav.directory": { en: "Directory", ar: "الدليل" },
  "nav.busesToday": { en: "Buses Today", ar: "الحافلات اليوم" },
  "busesToday.subtitle": { en: "Who's actually on each bus today, after approved one-day changes", ar: "من على كل حافلة فعليًا اليوم، بعد التغييرات المعتمدة ليوم واحد" },
  "busesToday.onboard": { en: "on board", ar: "على المتن" },
  "busesToday.joined": { en: "joined", ar: "انضموا" },
  "busesToday.left": { en: "on another bus", ar: "على حافلة أخرى" },
  "busesToday.none": { en: "No buses operating today.", ar: "لا توجد حافلات تعمل اليوم." },
  "busesToday.empty": { en: "No students on this bus today.", ar: "لا يوجد طلاب على هذه الحافلة اليوم." },
  "busesToday.joinedToday": { en: "joined today", ar: "انضم اليوم" },
  "busesToday.notToday": { en: "Not on this bus today", ar: "ليسوا على هذه الحافلة اليوم" },
  "busesToday.noSupervisor": { en: "No supervisor assigned", ar: "لا يوجد مشرف معيّن" },
  "common.reload": { en: "Reload", ar: "تحديث" },
  "dir.title": { en: "Supervisors & Drivers", ar: "المشرفون والسائقون" },
  "dir.subtitle": { en: "Contacts with today's route & bus.", ar: "جهات الاتصال مع مسار وحافلة اليوم." },
  "dir.supervisors": { en: "Supervisors", ar: "المشرفون" },
  "dir.busDrivers": { en: "Bus drivers", ar: "سائقو الحافلات" },
  "dir.noRoute": { en: "No route today", ar: "لا يوجد مسار اليوم" },
  "dir.call": { en: "Call", ar: "اتصال" },
  "dir.noPhone": { en: "No phone", ar: "لا يوجد هاتف" },
  "dir.none": { en: "None yet.", ar: "لا يوجد بعد." },
  "notif.title": { en: "Notifications", ar: "الإشعارات" },
  "notif.none": { en: "No notifications", ar: "لا توجد إشعارات" },
  "notif.soundOn": { en: "Turn notification sound on", ar: "تشغيل صوت الإشعارات" },
  "notif.soundOff": { en: "Mute notification sound", ar: "كتم صوت الإشعارات" },
  "notif.markAll": { en: "Mark all read", ar: "تعليم الكل كمقروء" },
  "pr.title": { en: "Profile Requests", ar: "طلبات تعديل البيانات" },
  "pr.subtitle": { en: "Parent-requested changes to their personal info — approve to apply.", ar: "طلبات تعديل البيانات الشخصية من أولياء الأمور — الموافقة تُطبّق التغيير." },
  "pr.none": { en: "No profile requests.", ar: "لا توجد طلبات." },
  "pr.field.name": { en: "Name", ar: "الاسم" },
  "pr.field.phone": { en: "Phone", ar: "الهاتف" },
  "pr.field.email": { en: "Email", ar: "البريد الإلكتروني" },
  "pr.current": { en: "Current", ar: "الحالي" },
  "pr.proposed": { en: "Requested", ar: "المطلوب" },
  "pr.approved": { en: "Request approved", ar: "تمت الموافقة" },
  "pr.rejected": { en: "Request rejected", ar: "تم الرفض" },
  "cr.title": { en: "Change Requests", ar: "طلبات التغيير" },
  "cr.subtitle": { en: "Parent-requested one-day bus changes to approve or reject.", ar: "طلبات تغيير الحافلة ليوم واحد من أولياء الأمور للموافقة أو الرفض." },
  "cr.none": { en: "No change requests.", ar: "لا توجد طلبات تغيير." },
  "cr.filterAll": { en: "All", ar: "الكل" },
  "cr.statusPending": { en: "Pending", ar: "قيد الانتظار" },
  "cr.statusApproved": { en: "Approved", ar: "تمت الموافقة" },
  "cr.statusRejected": { en: "Rejected", ar: "مرفوض" },
  "cr.requestedBy": { en: "Requested by", ar: "بواسطة" },
  "cr.forDate": { en: "For", ar: "ليوم" },
  "cr.dropOff": { en: "Drop-off", ar: "محطة النزول" },
  "cr.currentBus": { en: "Current bus (leaving)", ar: "الحافلة الحالية (المغادرة)" },
  "cr.requestedBus": { en: "Requested bus (joining)", ar: "الحافلة المطلوبة (الانضمام)" },
  "cr.route": { en: "Route", ar: "المسار" },
  "cr.now": { en: "now", ar: "الآن" },
  "cr.after": { en: "after", ar: "بعد" },
  "cr.seatsFree": { en: "seats free", ar: "مقاعد متاحة" },
  "cr.capacity": { en: "capacity", ar: "السعة" },
  "cr.full": { en: "FULL — would exceed capacity", ar: "ممتلئة — ستتجاوز السعة" },
  "cr.noCapacity": { en: "No capacity set", ar: "لم تُحدَّد السعة" },
  "cr.approve": { en: "Approve", ar: "موافقة" },
  "cr.reject": { en: "Reject", ar: "رفض" },
  "cr.approved": { en: "Request approved", ar: "تمت الموافقة على الطلب" },
  "cr.rejected": { en: "Request rejected", ar: "تم رفض الطلب" },
  "cr.forceTitle": { en: "Bus would exceed capacity", ar: "ستتجاوز الحافلة سعتها" },
  "cr.forceConfirm": { en: "Approve anyway (overbook)", ar: "الموافقة على أي حال (تجاوز السعة)" },
  "cr.forceCancel": { en: "Cancel", ar: "إلغاء" },
  "students.new": { en: "New student", ar: "طالب جديد" },
  "students.edit": { en: "Edit student", ar: "تعديل الطالب" },
  "students.subtitle": { en: "students", ar: "طالب" },
  "students.parentEmail": { en: "Parent email", ar: "بريد ولي الأمر" },
  "students.parentPhone": { en: "Parent phone", ar: "هاتف ولي الأمر" },
  "students.studentPhone": { en: "Student phone", ar: "هاتف الطالب" },
  "students.grade": { en: "Grade / year", ar: "الصف / السنة" },
  "students.class": { en: "Class", ar: "الفصل" },
  "students.dropOffStop": { en: "Drop-off stop", ar: "محطة النزول" },
  "students.dropOffStopHint": { en: "Pick a route first", ar: "اختر المسار أولاً" },
  "students.dropOffNone": { en: "No drop-off stop", ar: "بدون محطة نزول" },
  "students.linkedExisting": { en: "Student added and linked to the existing parent account:", ar: "تمت إضافة الطالب وربطه بحساب ولي الأمر الحالي:" },
  "att.title": { en: "Attendance reports", ar: "تقارير الحضور" },
  "att.subtitle": { en: "Export student attendance to Excel or PDF.", ar: "تصدير حضور الطلاب إلى Excel أو PDF." },
  "att.scopeAll": { en: "All students", ar: "كل الطلاب" },
  "att.scopeStudent": { en: "One student (monthly)", ar: "طالب واحد (شهري)" },
  "att.route": { en: "Route (optional)", ar: "المسار (اختياري)" },
  "att.student": { en: "Student", ar: "الطالب" },
  "att.month": { en: "Month", ar: "الشهر" },
  "att.from": { en: "From", ar: "من" },
  "att.to": { en: "To", ar: "إلى" },
  "att.columns": { en: "Columns to include", ar: "الأعمدة المضمّنة" },
  "att.format": { en: "Format", ar: "الصيغة" },
  "att.include": { en: "Records to include", ar: "السجلات المضمّنة" },
  "att.incBoth": { en: "Both", ar: "الكل" },
  "att.incPresent": { en: "Present only", ar: "الحاضرون فقط" },
  "att.incAbsent": { en: "Absent only", ar: "الغائبون فقط" },
  "att.export": { en: "Export", ar: "تصدير" },
  "att.allRoutes": { en: "All routes", ar: "كل المسارات" },
  "att.pickStudent": { en: "Select a student…", ar: "اختر طالبًا…" },
  "nav.vehicles": { en: "Vehicles", ar: "المركبات" },
  "busDrivers.new": { en: "New bus driver", ar: "سائق حافلة جديد" },
  "busDrivers.edit": { en: "Edit bus driver", ar: "تعديل سائق الحافلة" },
  "busDrivers.deleteConfirm": { en: "Delete this bus driver? This can't be undone.", ar: "حذف سائق الحافلة هذا؟ لا يمكن التراجع." },
  "busDrivers.subtitle": { en: "The people who physically drive the buses (no app login).", ar: "الأشخاص الذين يقودون الحافلات فعليًا (بدون دخول للتطبيق)." },
  "busDrivers.licenseValidity": { en: "License validity", ar: "صلاحية الرخصة" },
  "busDrivers.expired": { en: "Expired", ar: "منتهية" },
  "vehicles.capacity": { en: "Capacity (seats)", ar: "السعة (مقاعد)" },
  "assign.busDriver": { en: "Bus driver (optional)", ar: "سائق الحافلة (اختياري)" },
  "assign.busDriverName": { en: "Bus driver name", ar: "اسم سائق الحافلة" },
  "assign.busDriverPhone": { en: "Bus driver phone", ar: "هاتف سائق الحافلة" },
  "nav.routes": { en: "Routes", ar: "المسارات" },
  "nav.assignments": { en: "Assignments", ar: "التكليفات" },
  "nav.trips": { en: "Trips", ar: "الرحلات" },
  "nav.alerts": { en: "Alerts", ar: "التنبيهات" },
  "nav.reports": { en: "Reports", ar: "التقارير" },
  "nav.settings": { en: "Settings", ar: "الإعدادات" },
  "nav.organizations": { en: "Organizations", ar: "المؤسسات" },
  "nav.finance": { en: "Finance", ar: "المالية" },
  "nav.users": { en: "Users", ar: "المستخدمون" },

  // --- header ---------------------------------------------------------------
  "header.signedInAs": { en: "Signed in as", ar: "مسجّل الدخول باسم" },
  "header.signOut": { en: "Sign out", ar: "تسجيل الخروج" },
  "header.viewingAs": { en: "Viewing as", ar: "العرض باسم" },
  "header.impersonation": { en: "impersonation", ar: "انتحال" },
  "header.exitImpersonation": { en: "Exit impersonation", ar: "إنهاء الانتحال" },

  // --- login ----------------------------------------------------------------
  "login.adminTitle": { en: "Fleet Admin", ar: "إدارة الأسطول" },
  "login.adminSubtitle": { en: "Super admin panel", ar: "لوحة المشرف العام" },
  "login.managerTitle": { en: "Fleet Manager", ar: "مدير الأسطول" },
  "login.managerSubtitle": { en: "Organization sign in", ar: "تسجيل دخول المؤسسة" },
  "login.signIn": { en: "Sign in", ar: "تسجيل الدخول" },
  "login.authorizedOnly": { en: "Authorized platform operators only.", ar: "لمشغّلي المنصّة المصرّح لهم فقط." },
  "login.orgHint": { en: "Sign in with your organization username.", ar: "سجّل الدخول باسم المستخدم الخاص بمؤسستك." },

  // --- alerts ---------------------------------------------------------------
  "alerts.subtitle": { en: "Notifications and the rules that drive them", ar: "الإشعارات والقواعد التي تُنشئها" },
  "alerts.tabAlerts": { en: "Alerts", ar: "التنبيهات" },
  "alerts.tabRules": { en: "Rules", ar: "القواعد" },
  "alerts.allTypes": { en: "All types", ar: "كل الأنواع" },
  "alerts.readAndUnread": { en: "Read & unread", ar: "المقروء وغير المقروء" },
  "alerts.unread": { en: "Unread", ar: "غير مقروء" },
  "alerts.read": { en: "Read", ar: "مقروء" },
  "alerts.markRead": { en: "Mark read", ar: "تعليم كمقروء" },
  "alerts.markAllRead": { en: "Mark all as read", ar: "تعليم الكل كمقروء" },
  "alerts.editRule": { en: "Edit rule", ar: "تعديل القاعدة" },
  "alerts.when": { en: "When", ar: "الوقت" },
  "alerts.noAlerts": { en: "No alerts.", ar: "لا توجد تنبيهات." },
  "alerts.rulesTitle": { en: "Alert rules", ar: "قواعد التنبيه" },
  "alerts.newRule": { en: "New rule", ar: "قاعدة جديدة" },
  "alerts.threshold": { en: "Threshold", ar: "الحد" },
  "alerts.target": { en: "Target", ar: "النطاق" },
  "alerts.appliesTo": { en: "Applies to", ar: "ينطبق على" },
  "alerts.targetAll": { en: "All", ar: "الكل" },
  "alerts.targetVehicles": { en: "Specific vehicles", ar: "مركبات محددة" },
  "alerts.targetDrivers": { en: "Specific drivers", ar: "سائقون محددون" },
  "alerts.notifyVia": { en: "Notify via", ar: "التنبيه عبر" },
  "alerts.panel": { en: "Panel", ar: "اللوحة" },
  "alerts.comingSoon": { en: "coming soon", ar: "قريبًا" },
  "alerts.noRules": { en: "No rules.", ar: "لا توجد قواعد." },
  "alerts.shortStopNote": { en: "short_stop uses each stop's required dwell time — no threshold needed.", ar: "يستخدم short_stop مدة التوقف المطلوبة لكل محطة — لا حاجة لحد." },
  "alerts.ruleOff": { en: "off", ar: "متوقف" },

  // --- dashboard summary ----------------------------------------------------
  "summary.totalDrivers": { en: "Total drivers", ar: "إجمالي السائقين" },
  "summary.online": { en: "Online", ar: "متصل" },
  "summary.offline": { en: "Offline", ar: "غير متصل" },
  "summary.workingNow": { en: "Working now", ar: "يعمل الآن" },
  "summary.topDriver": { en: "Top driver this month", ar: "أفضل سائق هذا الشهر" },
  "summary.actualKm": { en: "Actual km", ar: "الكيلومترات الفعلية" },
  "summary.trips": { en: "Trips", ar: "الرحلات" },
  "summary.score": { en: "Score", ar: "النتيجة" },
  "summary.liveAlerts": { en: "Live alerts", ar: "تنبيهات مباشرة" },
  "summary.noTripsMonth": { en: "No trips recorded this month.", ar: "لا توجد رحلات مسجّلة هذا الشهر." },

  // --- full view ------------------------------------------------------------
  "full.activeDrivers": { en: "Active drivers", ar: "السائقون النشطون" },
  "full.drivers": { en: "Drivers", ar: "السائقون" },
  "full.selectAll": { en: "Select all", ar: "تحديد الكل" },
  "full.selectedCount": { en: "selected", ar: "محدد" },
  "full.noDrivers": { en: "No drivers with recent activity.", ar: "لا يوجد سائقون نشطون مؤخرًا." },
  "full.lastSeen": { en: "Last seen", ar: "آخر ظهور" },
  "full.onTripNow": { en: "On a trip now", ar: "في رحلة الآن" },
  "full.lastTrip": { en: "Last trip", ar: "آخر رحلة" },
  "full.ago": { en: "ago", ar: "منذ" },
  "full.justNow": { en: "just now", ar: "الآن" },
  "full.showRoute": { en: "Show route on map", ar: "إظهار المسار على الخريطة" },
  "full.hideRoute": { en: "Hide route", ar: "إخفاء المسار" },
  "full.routesShown": { en: "Routes shown", ar: "المسارات المعروضة" },
  "full.clearRoutes": { en: "Clear", ar: "مسح" },
  "full.noRoute": { en: "No route", ar: "لا يوجد مسار" },
  "full.noAssignment": { en: "No current assignment", ar: "لا يوجد تكليف حالي" },
  "full.assignmentsToday": { en: "assignments today", ar: "تكليفات اليوم" },
  "full.currentAssignment": { en: "Current assignment", ar: "التكليف الحالي" },
  "full.viewAll": { en: "All drivers", ar: "كل السائقين" },
  "full.viewGroups": { en: "Groups", ar: "المجموعات" },
  "full.newGroup": { en: "New group", ar: "مجموعة جديدة" },
  "full.newSubgroup": { en: "New subgroup", ar: "مجموعة فرعية" },
  "full.rename": { en: "Rename", ar: "إعادة تسمية" },
  "full.deleteGroup": { en: "Delete group", ar: "حذف المجموعة" },
  "full.ungrouped": { en: "Ungrouped", ar: "بدون مجموعة" },
  "full.groupNamePrompt": { en: "Group name:", ar: "اسم المجموعة:" },
  "full.selectGroup": { en: "Select all in group", ar: "تحديد كل المجموعة" },
  "full.dropHere": { en: "Drop here", ar: "أفلت هنا" },
  "full.emptyGroup": { en: "Empty — drag drivers here", ar: "فارغة — اسحب السائقين هنا" },
  "full.noGroups": { en: "No groups yet. Create one, then drag drivers in.", ar: "لا توجد مجموعات بعد. أنشئ واحدة ثم اسحب السائقين إليها." },
  "full.dragHint": { en: "Drag a driver into a group, or a group onto another to nest.", ar: "اسحب سائقًا إلى مجموعة، أو مجموعة فوق أخرى للتداخل." },
  "full.mapPlaceholder": { en: "Live map — Mapbox integration coming here", ar: "الخريطة المباشرة — تكامل Mapbox قادم هنا" },
  "full.mapSub": { en: "Drivers will render as points labeled with their current vehicle.", ar: "ستظهر السائقون كنقاط موسومة بمركباتهم الحالية." },
  "full.history": { en: "Driver path history will appear here (with the map)", ar: "سيظهر سجلّ مسار السائق هنا (مع الخريطة)" },
  "full.noActive": { en: "No drivers on an active trip right now.", ar: "لا يوجد سائقون في رحلة نشطة الآن." },
  "full.autoRefresh": { en: "auto-refresh 15s", ar: "تحديث تلقائي كل ١٥ ثانية" },
  "full.noPosition": { en: "no position yet", ar: "لا يوجد موقع بعد" },

  // --- settings -------------------------------------------------------------
  "settings.subtitle": { en: "Organization configuration", ar: "إعدادات المؤسسة" },
  "settings.trackingHours": { en: "Public tracking hours", ar: "ساعات التتبّع العامة" },
  "settings.tabTracking": { en: "Tracking hours", ar: "ساعات التتبع" },
  "settings.tabUsers": { en: "Users", ar: "المستخدمون" },
  "settings.tabSchool": { en: "School", ar: "المدرسة" },
  "settings.cutoffTitle": { en: "Change request cutoff time", ar: "وقت انتهاء طلبات التغيير" },
  "settings.cutoffLabel": { en: "Cutoff time", ar: "وقت الانتهاء" },
  "settings.cutoffHelp": { en: "Parents can't request a bus change for a day after this time the day before.", ar: "لا يمكن لأولياء الأمور طلب تغيير الحافلة ليوم ما بعد هذا الوقت في اليوم السابق." },
  "settings.tabCenters": { en: "Centers", ar: "المراكز" },
  "centers.subtitle": { en: "Your university/company hub locations. One is primary.", ar: "مواقع مركز جامعتك/شركتك. أحدها رئيسي." },
  "centers.namePh": { en: "Center name (e.g. Main Campus)", ar: "اسم المركز (مثل الحرم الرئيسي)" },
  "centers.searchHint": { en: "Search a place or click the map to set the location.", ar: "ابحث عن مكان أو انقر على الخريطة لتحديد الموقع." },
  "centers.add": { en: "Add center", ar: "إضافة مركز" },
  "centers.primary": { en: "Primary", ar: "رئيسي" },
  "centers.makePrimary": { en: "Make primary", ar: "تعيين كرئيسي" },
  "centers.none": { en: "No centers yet — add your university/hub.", ar: "لا توجد مراكز بعد — أضف جامعتك/مركزك." },
  "centers.deleteConfirm": { en: "Delete this center?", ar: "حذف هذا المركز؟" },
  "centers.pickFirst": { en: "Set a location on the map first.", ar: "حدّد موقعًا على الخريطة أولًا." },
  "centers.editing": { en: "Editing", ar: "جارٍ التعديل" },
  "full.distances": { en: "Distances", ar: "المسافات" },
  "full.toNextStop": { en: "To next stop", ar: "إلى المحطة التالية" },
  "full.toRouteEnd": { en: "To route end", ar: "إلى نهاية المسار" },
  "full.toCenter": { en: "To center", ar: "إلى المركز" },
  "full.nextStop": { en: "Next stop", ar: "المحطة التالية" },
  "full.noCenter": { en: "No center set", ar: "لم يُضبط مركز" },
  "full.calc": { en: "calculating…", ar: "جارٍ الحساب…" },
  "full.nearestRoute": { en: "Nearest route", ar: "أقرب مسار" },
  "full.nearestHint": { en: "Click the map (or search) to find the nearest route to a point.", ar: "انقر على الخريطة (أو ابحث) لإيجاد أقرب مسار إلى نقطة." },
  "full.nearestAway": { en: "away", ar: "بعيد" },
  "full.searchPlace": { en: "Search a place…", ar: "ابحث عن مكان…" },
  "settings.usersSubtitle": { en: "Managers, dispatchers and viewers in your organization.", ar: "المديرون والمرسلون والمشاهدون في مؤسستك." },
  "users.newUser2": { en: "New user", ar: "مستخدم جديد" },
  "users.editUser": { en: "Edit user", ar: "تعديل المستخدم" },
  "users.none": { en: "No users yet.", ar: "لا يوجد مستخدمون بعد." },
  "users.roleManager": { en: "Manager", ar: "مدير" },
  "users.roleDispatcher": { en: "Dispatcher", ar: "مرسل" },
  "users.roleViewer": { en: "Viewer", ar: "مشاهد" },
  "settings.current": { en: "Current", ar: "الحالي" },
  "settings.alwaysOnLabel": { en: "Always on (tracking live whenever a trip is active)", ar: "دائمًا مفعّل (تتبّع مباشر عند وجود رحلة نشطة)" },
  "settings.start": { en: "Start", ar: "البداية" },
  "settings.end": { en: "End", ar: "النهاية" },
  "settings.saved": { en: "Saved.", ar: "تم الحفظ." },

  // --- drivers / vehicles ---------------------------------------------------
  "drivers.newDriver": { en: "New driver", ar: "سائق جديد" },
  "drivers.editDriver": { en: "Edit driver", ar: "تعديل السائق" },
  "drivers.newSupervisor": { en: "New supervisor", ar: "مشرف جديد" },
  "drivers.editSupervisor": { en: "Edit supervisor", ar: "تعديل المشرف" },
  "drivers.deleteConfirmSupervisor": { en: "Delete this supervisor? This can't be undone.", ar: "حذف هذا المشرف؟ لا يمكن التراجع." },
  "drivers.appLoginSupervisor": { en: "Supervisor created. Their app login:", ar: "تم إنشاء المشرف. بيانات دخول التطبيق:" },
  "drivers.license": { en: "License number", ar: "رقم الرخصة" },
  "drivers.nationalId": { en: "National ID", ar: "الرقم القومي" },
  "drivers.licenseStart": { en: "License start", ar: "بداية الرخصة" },
  "drivers.licenseExpiry": { en: "License expiry", ar: "انتهاء الرخصة" },
  "drivers.deleteConfirm": { en: "Delete this driver? This can't be undone.", ar: "حذف هذا السائق؟ لا يمكن التراجع." },
  "drivers.currentVehicle": { en: "Current vehicle", ar: "المركبة الحالية" },
  "drivers.appLogin": { en: "Driver created. Their app login:", ar: "تم إنشاء السائق. بيانات دخول التطبيق:" },
  "drivers.addAnother": { en: "Add another", ar: "إضافة آخر" },
  "vehicles.newVehicle": { en: "New vehicle", ar: "مركبة جديدة" },
  "vehicles.editVehicle": { en: "Edit vehicle", ar: "تعديل المركبة" },
  "vehicles.deleteConfirm": { en: "Delete this vehicle? This can't be undone.", ar: "حذف هذه المركبة؟ لا يمكن التراجع." },
  "vehicles.busNumber": { en: "Bus number", ar: "رقم الحافلة" },
  "vehicles.plate": { en: "Plate", ar: "اللوحة" },
  "vehicles.trackingLink": { en: "Passenger tracking link", ar: "رابط تتبّع الركّاب" },
  "vehicles.copy": { en: "Copy", ar: "نسخ" },
  "vehicles.copied": { en: "Copied", ar: "تم النسخ" },

  // --- routes ---------------------------------------------------------------
  "routes.newRoute": { en: "New route", ar: "مسار جديد" },
  "routes.totalKm": { en: "Total km", ar: "إجمالي الكيلومترات" },
  "routes.estMinutes": { en: "Est. minutes", ar: "الدقائق التقديرية" },
  "routes.stops": { en: "Stops", ar: "المحطات" },
  "routes.mapPickerNote": { en: "map picker coming later — enter lat/lng manually", ar: "منتقي الخريطة لاحقًا — أدخل الإحداثيات يدويًا" },
  "routes.addStop": { en: "Add stop", ar: "إضافة محطة" },

  // --- assignments ----------------------------------------------------------
  "assign.newAssignment": { en: "New assignment", ar: "تكليف جديد" },
  "assign.shift": { en: "Shift", ar: "الوردية" },
  "assign.start": { en: "Start", ar: "البداية" },
  "assign.tripDate": { en: "Trip date", ar: "تاريخ الرحلة" },
  "assign.assign": { en: "Assign", ar: "تكليف" },
  "assign.select": { en: "Select…", ar: "اختر…" },
  "assign.clear": { en: "Clear", ar: "مسح" },
  "assign.none": { en: "No assignments.", ar: "لا توجد تكليفات." },
  "assign.end": { en: "End", ar: "النهاية" },
  "assign.endTime": { en: "End time", ar: "وقت الانتهاء" },
  "assign.editAssignment": { en: "Edit assignment", ar: "تعديل التكليف" },
  "assign.save": { en: "Save changes", ar: "حفظ التغييرات" },
  "assign.deleteConfirm": { en: "Delete this assignment? This can't be undone.", ar: "حذف هذا التكليف؟ لا يمكن التراجع عن هذا الإجراء." },
  "assign.endAfterStart": { en: "End time must be after the start time.", ar: "يجب أن يكون وقت الانتهاء بعد وقت البدء." },
  "assign.conflictDriver": { en: "Driver {name} is already assigned to {route} from {start}–{end}.", ar: "السائق {name} مُسند بالفعل إلى {route} من {start} إلى {end}." },
  "assign.conflictVehicle": { en: "Bus {name} is already busy on another assignment from {start}–{end}.", ar: "الحافلة {name} مشغولة بالفعل في تكليف آخر من {start} إلى {end}." },
  "assign.conflictGeneric": { en: "This driver or vehicle is already booked for an overlapping time.", ar: "هذا السائق أو المركبة محجوز بالفعل في وقت متداخل." },

  // --- reports --------------------------------------------------------------
  "reports.subtitle": { en: "Combine report types over a period", ar: "ادمج أنواع التقارير على مدى فترة" },
  "reports.stepSubject": { en: "1 · Subject", ar: "١ · الموضوع" },
  "reports.stepType": { en: "2 · Report type", ar: "٢ · نوع التقرير" },
  "reports.stepPeriod": { en: "3 · Period", ar: "٣ · الفترة" },
  "reports.pickSubject": { en: "Choose one", ar: "اختر واحدًا" },
  "reports.searchSubject": { en: "Search…", ar: "بحث…" },
  "reports.subjectLabel": { en: "Subject", ar: "الموضوع" },
  "reports.change": { en: "Change", ar: "تغيير" },
  "reports.emptyResult": { en: "Pick a subject, a report type and a period, then Generate.", ar: "اختر موضوعًا ونوع تقرير وفترة، ثم أنشئ." },
  "reports.result": { en: "Report", ar: "التقرير" },
  "reports.scheduleTitle": { en: "Schedule to email", ar: "جدولة عبر البريد" },
  "reports.scheduleHint": { en: "Set up a recurring emailed report. Email delivery is coming soon.", ar: "إعداد تقرير دوري عبر البريد. إرسال البريد قريبًا." },
  "reports.frequency": { en: "Frequency", ar: "التكرار" },
  "reports.daily": { en: "Daily", ar: "يومي" },
  "reports.weekly": { en: "Weekly", ar: "أسبوعي" },
  "reports.monthly": { en: "Monthly", ar: "شهري" },
  "reports.emailAddress": { en: "Email address", ar: "البريد الإلكتروني" },
  "reports.addSchedule": { en: "Add schedule", ar: "إضافة جدول" },
  "reports.scheduledReports": { en: "Scheduled reports", ar: "التقارير المجدولة" },
  "reports.noSchedules": { en: "No schedules yet.", ar: "لا توجد جداول بعد." },
  "reports.deliverySoon": { en: "Delivery coming soon", ar: "الإرسال قريبًا" },
  "reports.allSubjects": { en: "All", ar: "الكل" },
  "reports.generate": { en: "Generate", ar: "إنشاء" },
  "reports.downloadPdf": { en: "Download PDF", ar: "تنزيل PDF" },
  "reports.period": { en: "Period", ar: "الفترة" },
  "reports.today": { en: "Today", ar: "اليوم" },
  "reports.week": { en: "This week", ar: "هذا الأسبوع" },
  "reports.month": { en: "This month", ar: "هذا الشهر" },
  "reports.custom": { en: "Custom", ar: "مخصص" },
  "reports.from": { en: "From", ar: "من" },
  "reports.to": { en: "To", ar: "إلى" },
  "reports.plannedKm": { en: "Planned km", ar: "كم مخطط" },
  "reports.actualKm": { en: "Actual km", ar: "كم فعلي" },
  "reports.diff": { en: "Diff", ar: "الفرق" },

  // --- super-admin: organizations ------------------------------------------
  "orgs.total": { en: "total", ar: "الإجمالي" },
  "orgs.newOrg": { en: "New organization", ar: "مؤسسة جديدة" },
  "orgs.plan": { en: "Plan", ar: "الخطة" },
  "orgs.module": { en: "Module", ar: "الوحدة" },
  "orgs.features": { en: "Features", ar: "الميزات" },
  "orgs.moduleUniversity": { en: "University", ar: "جامعة" },
  "orgs.moduleSchool": { en: "School", ar: "مدرسة" },
  "orgs.monthlyFee": { en: "Monthly fee", ar: "الرسوم الشهرية" },
  "orgs.expiry": { en: "Expiry", ar: "الانتهاء" },
  "orgs.suspend": { en: "Suspend", ar: "تعليق" },
  "orgs.activate": { en: "Activate", ar: "تفعيل" },
  "orgs.login": { en: "Login", ar: "دخول" },

  // --- super-admin: finance -------------------------------------------------
  "finance.subtitle": { en: "Subscriptions & collections across the platform", ar: "الاشتراكات والتحصيلات عبر المنصّة" },
  "finance.totalExpected": { en: "Total expected", ar: "إجمالي المتوقع" },
  "finance.totalCollected": { en: "Total collected", ar: "إجمالي المحصّل" },
  "finance.totalOutstanding": { en: "Total outstanding", ar: "إجمالي المستحق" },
  "finance.expected": { en: "Expected", ar: "المتوقع" },
  "finance.collected": { en: "Collected", ar: "المحصّل" },
  "finance.outstanding": { en: "Outstanding", ar: "المستحق" },

  // --- super-admin: users ---------------------------------------------------
  "users.subtitle": { en: "Platform staff who help run the panel", ar: "موظفو المنصّة الذين يساعدون في تشغيل اللوحة" },
  "users.newUser": { en: "New user", ar: "مستخدم جديد" },
  "users.permissions": { en: "Permissions", ar: "الصلاحيات" },
};
